### ISSUE TITLE
Fix DST stuff

### ISSUE THREAD

**Issue by 153957** [HiSPARC/station-software#19]
Yesterday every station controller got a message saying that his station has Trigger rate errors. These were caused by DST issues (GPS/PC time difference etc..). This should be fixed.

**Comment by 153957** [comment]
Again! Summer time. The problem is mostly caused by the new HiSPARC DAQ which writes the time difference to `hisparc.ini` while the monitor checks `hisparcII.ini`.. In the next update we will unify this variables into the `hisparc.ini` so the monitor (`Check.py`) should also use it, or perhaps not at all, or try getting UTC time from the PC..

**Comment by davidfokkema** [comment]
Do we have an upgrade path?

**Comment by 153957** [comment]
Haha, That is another issue.

I was just lamenting today that the installer is so heavy (MySQL/Python/LabView RTE/...), it would be so nice if it worked just like PySPARC where it could just checkout a newer version from GitHub.
..grr arggh Windows..

**Comment by davidfokkema** [comment]
Sweet dreams, :-P

**Comment by tomkooij** [comment]
This was fixed in 4c5bc40b9379666f4e00aac64299a3cacc7f4723
All stations recieved a new hsmonitor in the python 2.7.15 + hsmonitor update (userUpdaterv14.exe pushed to all active stations on jan 18 2018)
