### ISSUE TITLE
Fix the Uploader to make sure it only sends events once

### ISSUE THREAD

**Issue by 153957** [HiSPARC/station-software#2]
Currently the Uploader may try to upload new events to the Nikhef server and due to network problems not finish within 30 seconds, causing the upload to timeout. When a timeout occurs the Python script will try to upload the events again in the next batch. However in the background Windows might still be trying to upload the events, which may succeed, and because Python is no longer listening to the response it is unaware that it actually succeeded. This will cause duplicate events on the server.

Here are some possible solutions:
http://stackoverflow.com/questions/8037724/how-to-shutdown-a-timed-out-http-post-using-urlopen-by-urllib2-in-python

The preferred solution:
- Simply kill the upload process in case of a timeout, so that a timeout is indeed a timeout.
  If multiple timeouts occur the batch size may need to be changed dynamically.

Other solutions may include extra server side scripts:
- The server collects a list hashes of received event batches, the client can check that list to see which events were successfully sent.
- Use a more robust send-response mechanism

**Comment by tomkooij** [comment]
I'm going to reenable the timeout by undoing cf63b81 (while switching to `requests`) soon. 

Rationale:
 - He handle duplicate events: [sapphire::ProcessEvents](https://github.com/HiSPARC/sapphire/blob/5456047a64a6bc11bd93707b5d936270c393cfc5/sapphire/analysis/process_events.py#L193)
 - The timeout causes hanging uploaders. (We currently have two stations with hanging uploaders behind a VPN...). 

I will set the timeout to as long as possible, but not infinite.

**Comment by davidfokkema** [comment]
I added the timeout nine years ago (87bb72a062744eefa0b97c5bb4d9006caa81faac) just to prevent the issue of stuck uploaders, 😜
