### ISSUE TITLE
Send configuration values in ADC counts instead of mV

### ISSUE THREAD

**Issue by 153957** [HiSPARC/station-software#27]
This would remove confusion about trigger levels during analysis.

**Comment by 153957** [comment]
Apparently not easy to implement in the LabView DAQ.
Perhaps do the conversion in the HiSPARC Monitor?

**Comment by davidfokkema** [comment]
Ouch.

**Comment by 153957** [comment]
Also discussed in HiSPARC/pysparc#24
PySPARC sends these as absolute ADC counts.

**Comment by 153957** [comment]
Fixed in c4fcab646baed1321aff1cc76138a2ce18d0e1e1

**Comment by 153957** [comment]
Grr, argghh! 
![600d95c1f42bf377a8790dc282b3839b](https://cloud.githubusercontent.com/assets/1433682/13529244/6d7f68de-e21b-11e5-891d-49def8344572.jpg)

This is very annoying.. wouldn't it be nice if the values in configs were always in ADC counts..

**Comment by davidfokkema** [comment]
Hahaha! I love the picture. But what is the problem right now? That you fixed the code but cannot distribute it to all detector pc's?

**Comment by 153957** [comment]
That is not a problem, the latest installer includes the new DAQ and new Monitor which should send the values as ADC to the datastore. Previously they were send as mV, and station 501 has some overlap where it uses the new DAQ with the old monitor, so baseline at 30, but thresholds in mV. Currently any negative valued thresholds are assumed to be relative to the 200 ADC count baseline (for the trigger settings TSV). I think I will modify the 501 configs in the datastore. Luckily I can base it on your script to fix the PySPARC configs :smile:

**Comment by davidfokkema** [comment]
Great that you can use my script! Switching conventions hurts.
