### ISSUE TITLE
Implement a station-status uploader

### ISSUE THREAD

**Issue by 153957** [HiSPARC/station-software#4]
We want to get rid off, or at least be less dependent on Nagios.

We want to make a new script separate of the HiSPARC Monitor to watch the status of the Detection, Software and the PC.
This will take over much of the functionality of Nagios.

It will attempt to send small messages (e.g. small Python dictionaries) on a regular interval (e.g. 5 minutes).
These should contain similar information to what Nagios asks to the server:
(percentage, absolute number, free, used or both?):
- System:
  - CPU usage
  - RAM usage
  - Disc Space usage
- Monitor
  - Event rate
  - Trigger rate
  - Storage size
  - Storage growth
- Weather station online
- ...

This program should have some interface showing the status of those items on the local PC.
We should also incorporate the functionality of the diagnostictool into this, providing a button which will run the checks and also send the results to the datastore.

(Part of) The status information that this sends should be made available on the public database.

The server should also periodically check that it has received an update from a station recently (e.g. last 15 minutes),
If this is not the case it should inform the contact for that station by email.

**Comment by tomkooij** [comment]
Superseded by #45
