### ISSUE TITLE
Errors starting software

### ISSUE THREAD

**Issue by 153957** [HiSPARC/station-software#40]
**Update**

Some stations appear to be fixable by replacing the `python` installation with one from the installer.

Fix status (for stations known to require fix):
- [x] 105
- [x] 501
- [x] 502
- [x] 504
- [x] 506
- [x] 508
- [x] 510
- [x] 511

**Original Issue**

Since the errors caused by tietar most stations needed to have the Monitor manually restarted. And most stations seem to have been working fine since. However, several stations have been giving Python errors while starting the software. They were working fine before. Reboots did not help..

Station 502:
![502_start_error](https://cloud.githubusercontent.com/assets/1433682/13201470/fafe3896-d872-11e5-9096-15ae58921308.png)

Station 506:
![506_start_error](https://cloud.githubusercontent.com/assets/1433682/13201471/fb204a3a-d872-11e5-9377-31f43d29d326.png)

**Comment by NiekSchultheiss** [comment]
Station 105
![screen shot 2016-02-23 at 13 00 07](https://cloud.githubusercontent.com/assets/1632409/13250975/a9171cac-da2d-11e5-8e07-2dfcc7538fd4.png)

**Comment by 153957** [comment]
Fixed on 501 by replacing the installed Python (`{HiSPARC_ROOT}/user/python`) by the one from the station-software on GitHub.

**Comment by davidfokkema** [comment]
The complete folder?

**Comment by 153957** [comment]
That is indeed what I did, seemed easier than digging around to find any/all faults.. especially since the problem appears to be different on each station.

**Comment by 153957** [comment]
Also worked on 504 and 510. Still busy downloading on other stations.
Unfortunately downloading takes a lot of time.. Since I'm downloading the entire station-software zip (400 MB) instead of just python.

**Comment by davidfokkema** [comment]
Oh well. I'm glad it works!

**Comment by 153957** [comment]
I went by 511 today, it required the Monitor to be killed (~2k processes).
Restarting the software fails, it also needs python replaced..

**Comment by davidfokkema** [comment]
Sigh

**Comment by 153957** [comment]
Science Park station are all up and running again.
Except 503, which is having some internet connectivity 'issues'..

**Comment by davidfokkema** [comment]
Great work!
