### ISSUE TITLE
Transition to Python 3

### ISSUE THREAD

**Issue by 153957** [HiSPARC/station-software#42]
Python 2 will be end-of-life in a few years.
Parts of the station-software should be transitioned to Python 3.
Does not need to keep backwards compatibility with Python 2.

See discussion at: https://github.com/HiSPARC/sapphire/pull/154#issuecomment-257255562

**Comment by tomkooij** [comment]
I looked into this (before updating python to 2.7.15).

The `TimedConcurrentLogging` stuff in `/user/pythonshared` is non-trivial to port to python3. This code implements a thread-safe, concurrent, rotating, logger. This is still an unsolved problem in python.

So let's not break stuff and keep this on python 2.7.
