### ISSUE TITLE
hsmonitor seems to hang on upload

### ISSUE THREAD

**Issue by tomkooij** [HiSPARC/station-software#48]
Sometimes (observed on station `fombureau1.his` every few days) the monitor will apparently hang on uploading events. 

Symptoms: `StorageSize` becomes very large. No events are uploaded. Fix: restart hsmonitor

Normal behaviour:
```
2019-02-13 20:38:46 (Uploader) hsmonitor.uploader.__getNumEventsToUpload.DEBUG: 0: Unblocked
2019-02-13 20:38:46 (BufferListener) hsmonitor.bufferlistener.clearBufferMessages.DEBUG: Clear 15 events from buffer...
2019-02-13 20:38:46 (Uploader) hsmonitor.uploader.run.INFO: 0: 100 events uploaded to http://frome.nikhef.nl/hisparc/upload.
2019-02-13 20:38:46 (Uploader) hsmonitor.storagemanager.setUploaded.DEBUG: 100 events removed from Storage
2019-02-13 20:38:46 (Uploader) hsmonitor.uploader.__getNumEventsToUpload.DEBUG: 0: Blocked: Too few events
2
```

Hang:
```
2019-02-13 20:39:44 (BufferListener) hsmonitor.uploader.notify.DEBUG: 0: 109 events pending.
2019-02-13 20:39:44 (Uploader) hsmonitor.uploader.__getNumEventsToUpload.DEBUG: 0: Unblocked
[...]
2019-02-13 20:39:54 (BufferListener) hsmonitor.uploader.notify.DEBUG: 0: 123 events pending.
[...]
2019-02-13 20:41:05 (BufferListener) hsmonitor.uploader.notify.DEBUG: 0: 241 events pending.
```
The uploader is still uploading, so will never upload the next batch.

I tracked this down to:
https://github.com/HiSPARC/station-software/blob/e9b14c652f96face7c1217b7c5d0486aa7bdde5b/user/hsmonitor/Uploader.py#L149

Appearantly `urllib2.urlopen` can hang indefinitely. As we now have `requests` on python 2.7.15 (from userUnpacker v14) we can just use requests.

**Comment by 153957** [comment]
+1 for requests

**Comment by davidfokkema** [comment]
+1!

**Comment by 153957** [comment]
Maybe related?

https://github.com/HiSPARC/station-software/commit/cf63b8193cfb62449031af6ec3a7703b4d7b818d
https://github.com/HiSPARC/station-software/issues/2

**Comment by tomkooij** [comment]
@153957: Thanks for pointing that out. So my observation that uploading can take "forever" is correct. Its a feature not a bug :)

I think replacing this with `requests` will possibly bring back the duplicate events. However this should not be an issue? Our processing of raw data should be (is) resistant to duplicate events???? It is at least something we can solve automatically, while "hsmonitor hanging op upload" needs human intervention.

**Comment by 153957** [comment]
You can also try reducing the minimum and maximum batch sizes for uploading. So FOM uploads more often and never in to large batches?
https://github.com/HiSPARC/station-software/blob/e9b14c652f96face7c1217b7c5d0486aa7bdde5b/user/hsmonitor/HsMonitor.py#L209-L210

**Comment by tomkooij** [comment]
That may be a work around, but I'll try to figure out if `requests` handles timeouts better, so this can be really fixed.

**Comment by tomkooij** [comment]
Last monday `supervisorctl` was not working on frome: https://github.com/Supervisor/supervisor/issues/480

Unfortunately it was very hard to restart supervisord in this state. I probably messed up and put the child `uwsgi` in some failed state. Eventually I just rebooted frome to be done with it.

This left >10 stations with a hanging uploader, ie the hsmontor was still waiting for the upload to finish, without timeout and frome was rebooted. Fortunately we pushed an update, so that we remotely restarted most of the hsmonitors.
However, after 4 days there still is a station that is waiting for the timeout (and VPN is blocked, so no remote access)

This needs to be fixed.

**Comment by tomkooij** [comment]
I'm going to reenable the timeout by undoing #2 / cf63b81 (while switching to `requests`) soon. 

Rationale:
 - He handle duplicate events: [sapphire::ProcessEvents](https://github.com/HiSPARC/sapphire/blob/5456047a64a6bc11bd93707b5d936270c393cfc5/sapphire/analysis/process_events.py#L193)
 - The timeout causes hanging uploaders. (We currently have two stations with hanging uploaders behind a VPN...). 

I will set the timeout to as long as possible, but not infinite.
