### ISSUE TITLE
Remove old updaters

### ISSUE THREAD

**Issue by 153957** [HiSPARC/station-software#8]
Currently all stations that have been updated keep those updates in the download folder. And some stations have been updated many times, with each update weighing in at ~100 MB, that adds up quickly. We have some machines out there that have very small hard drives (10 GB) so disc space can be precious, these machines should of course be replaced, but that is another problem.

We should include a check in the update program to delete any updates that have been (successfully) applied or are no longer needed (older ones).

**Comment by 153957** [comment]
We hardly ever update so not a big issue currently..

**Comment by tomkooij** [comment]
We are updating machines (Windows 10) as well, so this seems irrelevant. Closing.
